1. **You**: app.get("/books",(req,res)=>{
try{
const books = Book.find({})
}catch(error){
  console.log(error.message)
  res.status(500).send({message:error.message})
}
})

any mistake
2. **You**: app.get("/books",(req,res)=>{
try{
const books = Book.find({})
}catch(error){
  console.log(error.message)
  res.status(500).send({message:error.message})
}
})

any mistake